ARG baseimage

FROM ${baseimage}

# # Install Bower components
WORKDIR /app/piserver/piserver
RUN bower --allow-root install

# # Set default workdir
WORKDIR /app/piserver
# TODO Use nginx to serve static assets
# CMD /app/ops/entry.sh


# vim: ft=Dockerfile
