apiVersion: v1
kind: Service
metadata:
  labels:
    app: pira
  name: pira
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 8000
  selector:
    app: pira
status:
  loadBalancer: {}
