apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    app: pir
  name: pir
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: pir
status:
  loadBalancer: {}
