apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pires
  name: pires
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pires
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: TZ
          value: PST
        # - name: bootstrap.memory_lock
        #   value: "true"
        - name: xpack.security.enabled
          value: "false"
        image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
        name: pires
        resources:
          limits:
            cpu: "2"
            memor: 2048Mi
          requests:
            cpu: "2"
            memory: 2048Mi
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdatadir
      restartPolicy: Always
      volumes:
      - name: esdatadir
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: esdatadir
status: {}
