apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pirpg
  name: pirpg
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: pirpg
status:
  loadBalancer: {}
