apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    app: pirstatic
  name: pirstatic
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8000
  selector:
    app: pirstatic
status:
  loadBalancer: {}
