apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    app: pirstatic
  name: pirstatic
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pirstatic
    spec:
      containers:
      - env:
        - name: DJANGO_DEBUG
          value: "True"
        - name: DOMAIN_NAMES
          value: 0.0.0.0 localhost
        - name: ELASTICSEARCH_PREFIX
          value: pir
        - name: ESHOST
          value: pires
        - name: ESPORT
          value: "9200"
        - name: PGDBNAME
          value: pir_arches_db
        - name: PGHOST
          value: pirpg
        - name: PGPASSWORD
          value: postgres
        - name: PGPORT
          value: "5432"
        - name: PGUSERNAME
          value: postgres
        - name: TZ
          value: PST
        image: pir_static:v0.11
        name: pirstatic
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
