---
version: '3.2'
services:
  pir:
    container_name: pir_local
    image: pir_local:dev
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - INSTALL_DEFAULT_GRAPHS=True
      - INSTALL_DEFAULT_CONCEPTS=True
      - PGUSERNAME=postgres
      - PGPASSWORD=postgres
      - PGDBNAME=pir_arches_db
      - PGHOST=pirpg
      - PGPORT=5432
      - ESHOST=pires
      - ESPORT=9200
      - ELASTICSEARCH_PREFIX=pir
      - DJANGO_MODE=dev
      - DJANGO_DEBUG=True
      # - DJANGO_REMOTE_DEBUG=False
      - DOMAIN_NAMES=0.0.0.0
      - TZ=PST
    ports:
      - '8000:8000'
    depends_on:
      - pirpg
      - pires
    volumes:
      - type: bind
        source: .
        target: /app/piserver
  pirpg:
    container_name: pirpg
    image: mdillon/postgis:9.6-alpine
    volumes:
      - pgdatadir:/var/lib/postgresql/data
      - pglogdir:/var/log/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=PST
  pires:
    container_name: pires
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    volumes:
      - esdatadir:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=PST
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pgdatadir:
  pglogdir:
  esdatadir:
